name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - attrs=25.4.0=pyh71513ae_0
  - blosc=1.21.6=h85f69ea_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py312hf90b1b7_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h9214b88_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=h8276f4a_0
  - gdal=3.10.0=py312h315a139_6
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.4=h887f4e7_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.7.7=h88ece9c_0
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=2_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=2_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_12
  - libgdal-core=3.10.0=ha193a43_5
  - libgomp=15.2.0=h8ee18e1_12
  - libheif=1.18.2=gpl_hc631cee_100
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=2_hf9ab0e9_mkl
  - libpng=1.6.51=h7351971_0
  - libpq=18.1=h7c87ebf_1
  - librttopo=1.1.0=hd4c2148_17
  - libspatialite=5.1.0=h939089a_12
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.6=h4fa8253_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - minizip=4.0.6=hb638d1e_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - numpy=2.3.5=py312ha72d056_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hc128f0a_1
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py312h5ee8bfe_3
  - pip=25.3=pyhc872135_0
  - proj=9.5.1=h4f671f6_0
  - psycopg2=2.9.10=py312h2f859cb_4
  - pthread-stubs=0.4=h0e40799_1002
  - pycparser=2.22=pyh29332c3_1
  - pyogrio=0.10.0=py312h6e88f47_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.1=py312ha24589b_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=2_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - rasterio=1.4.3=py312hc0daee4_0
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h91ac024_0
  - setuptools=80.9.0=py312haa95532_0
  - shapely=2.0.7=py312h0c580ee_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py312he06e257_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x265=3.5=h2d74725_3
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - greenlet==3.2.4
      - python-dotenv==1.2.1
      - schedule==1.2.2
      - scipy==1.16.3
      - sqlalchemy==2.0.44
      - typing-extensions==4.15.0
prefix: C:\Users\admin\miniconda3\envs\geo
